### ISSUE TITLE
EXCEPTION! undefined local variable or method `enable_browser' for main:Object

### ISSUE THREAD

**Issue by manis-ai** [intrigueio/intrigue-ident#14]
Trying to run the docker image and give it a list of URLs to scan with browser enabled:
docker run -v /root/urls:/mnt/localurls -t intrigueio/intrigue-ident --file /mnt/localurls/targeturls.txt  --browser true

Get an error:
EXCEPTION! undefined local variable or method `enable_browser' for main:Object
Traceback (most recent call last):
from ./util/ident.rb:291:in `<main>'
from ./util/ident.rb:281:in `main'
from ./util/ident.rb:99:in `check_file_urls'
./util/ident.rb:99:in `pop': queue empty (ThreadError)

It seems to me, that the variable enable_browser is not defined in function check_file_urls in util/ident.rb, thus the error.

**Comment by jcran** [comment]
Thanks for the report, looking into this. 

Browser support in Intrigue Core has moved to a separate service (standalone devtools API listener). This will need to be ported to ident. Shouldn't be too much work, given that it's pretty stable and tested in core (client: https://github.com/intrigueio/intrigue-core/blob/master/lib/client/chrome_browser.rb). Challenge will be making sure the service is up and started in the docker container, will think on this and come up with a solution. 

Just fyi, the browser isnt used by many checks (only checks of type :content_dom) in ident, you'll be able to get the vast majority of the value out  by running the cli tool without it.

Any particular problem you're trying to solve with the browser?

**Comment by manis-ai** [comment]
That's ok - just trying out the tool and was surprised by the error. I'll leave the browser argument out.

**Comment by jcran** [comment]
No longer relevant, as browser work has been discontinued in this project, and more deeply integrated into the overarching intrigue-core project
