### ISSUE TITLE
`ident_create_browser_session': uninitialized constant Intrigue::Config

### ISSUE THREAD

**Issue by manis-ai** [intrigueio/intrigue-ident#15]
Trying to run docker image for a single url with browser enabled:
docker run -t intrigueio/intrigue-ident --browser true --url https://google.com

Get an error:
Checking URL: https://google.com
Traceback (most recent call last):
	from ./util/ident.rb:291:in `<main>'
	from ./util/ident.rb:275:in `main'
	from ./util/ident.rb:156:in `check_single_url'
	from /home/ident/lib/ident.rb:192:in `generate_http_requests_and_check'
	from /home/ident/lib/ident.rb:192:in `each'
	from /home/ident/lib/ident.rb:218:in `block in generate_http_requests_and_check'
/home/ident/lib/http/browser.rb:17:in `ident_create_browser_session': uninitialized constant Intrigue::Config (NameError)

**Comment by jcran** [comment]
No longer relevant, as browser work has been discontinued in this project, and more deeply integrated into the overarching intrigue-core project
