### ISSUE TITLE
Ident should use JSON to hold its fingerprints instead of Ruby hashmaps

### ISSUE THREAD

**Issue by ghostlulzhacks** [intrigueio/intrigue-ident#19]
Using JSON files or any other non language specific data storage format to hold your fingerprints will make it a lot easier for other languages to use your fingerprints. You have done some amazing work here I and I'm sure others would love to use your fingerprints in our personal tools.

**Comment by jcran** [comment]
Some checks cannot be easily expressed in JSON due to the dynamic grabbers / inference, hence the need for expressing in a turing complete language. That said, you can access the bulk of the checks in json here: https://app.intrigue.io/api/ident/checks/http
