### ISSUE TITLE
nginx fingerprinting not working correctly (possibly because of the redirect)

### ISSUE THREAD

**Issue by jen140** [intrigueio/intrigue-ident#20]
Running the latest docker image one host doesn't fingerprint the server as nginx.

How to reproduce:
docker pull intrigueio/intrigue-ident && docker run -t intrigueio/intrigue-ident --url http://server.amconstruct1.com:8080

Output:
```
Checking URL: http://server.amconstruct1.com:8080
Fingerprint:
```

curl --head http://server.amconstruct1.com:8080
```
HTTP/1.1 302 Found
cache-control: max-age=0, private, must-revalidate
connection: close
content-length: 11
date: Thu, 12 Mar 2020 14:51:32 GMT
location: http://survey-smiles.com
server: nginx
set-cookie: sid=f6e916ac-6470-11ea-9d4c-692b809f72b1; path=/; domain=.amconstruct1.com; expires=Tue, 30 Mar 2088 18:05:39 GMT; max-age=2147483647; HttpOnly
```

Expected output(example domain "DISTINCTIVEINDUSTRIES.com" was used, it also reports simple "server: nginx" ):
```
Checking URL: http://DISTINCTIVEINDUSTRIES.com
Fingerprint:
 - Nginx Nginx   - Nginx (CPE: cpe:2.3:a:nginx:nginx::) (Tags: ["Web Server"]) (Hide: false)
```

curl --head http://DISTINCTIVEINDUSTRIES.com
```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 12 Mar 2020 14:51:15 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Expires: Wed, 17 Aug 2005 00:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: 2863bf481cda1bd44e4fb03af25b5843=f454d5edd431232714564a97f54a7b86; path=/; HttpOnly
Last-Modified: Thu, 12 Mar 2020 14:51:15 GMT
```

**Comment by jen140** [comment]
Another domain that has similar characteristics (not detecting something after the redirect):

curl --head http://docs.nvdems.com
``` 
HTTP/1.1 302 Found
Location: http://drive.google.com/a/nvdems.com
Date: Fri, 13 Mar 2020 12:08:24 GMT
Content-Type: text/html; charset=UTF-8
Server: ghs
Content-Length: 233
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
``` 

Output:
``` 
Checking URL: http://docs.nvdems.com
Fingerprint:
``` 

While google (ghs header) is working correctly in hosts without a redirect:
curl --head http://ghs.google.com
``` 
HTTP/1.1 404 Not Found
Date: Fri, 13 Mar 2020 12:09:50 GMT
Content-Type: text/html; charset=UTF-8
Server: ghs
Content-Length: 1561
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
``` 

Output:
```
Checking URL: http://ghs.google.com
Fingerprint:
 - Google Hosted   - server header (CPE: cpe:2.3:s:google:hosted::) (Tags: ["Hosting"]) (Hide: false)
 - Google Hosted   - Google Missing Page (CPE: cpe:2.3:s:google:hosted::) (Tags: ["Hosting"]) (Hide: true)
```

**Comment by jcran** [comment]
I think there's something going on related to the way the dynamic_version is captured. the check was written in such a way that it would match anything with "server: nginx" - but there was also a dynamic_version grabber that would have failed in the case where no version was supplied. 

I've (at least) temporarily fixed this by separating the cases, namely 1) adding a no-version nginx check and 2) adding a version-based check that verifies we first have a version. This addresses the immediate issue: 

```
jcran ident master [20200317]$ ./uti./util/ident.rb -d -u http://server.amconstruct1.com:8080
Checking URL: http://server.amconstruct1.com:8080
Getting http://server.amconstruct1.com:8080
Getting http://server.amconstruct1.com:8080/api
Getting http://server.amconstruct1.com:8080/doesntexist-123
Getting http://server.amconstruct1.com:8080/WebResource.asmx
Getting http://server.amconstruct1.com:8080/admin
Getting http://server.amconstruct1.com:8080/error.json
Ran 576 checks against base URL
Fingerprint:
 - Nginx Nginx   - Nginx (no version) (CPE: cpe:2.3:a:nginx:nginx::) (Tags: ["Web Server"]) (Hide: false)

```

However, in my opinion, the tool should still fingerprint (and return a FP without a version) in cases where the match_* item matches, but the dynamic_version fails. Thoughts?

**Comment by jcran** [comment]
Unable to repro the first issue, but the second was related to how redirection was parsed out and followed. Thats been addressed in https://github.com/intrigueio/intrigue-ident/commit/974063f09fe55087a248b0d8f93449c59fff2dae

**Comment by jcran** [comment]
After a little more digging it's become clear that we need an approach to fingerprint ... along the way (vs just the final url). Currently we're stuck between doing either the first hit, or the final url. It'd be handy if we checked every url as we went along the path. Going to open a new issue for this.
