### ISSUE TITLE
Error with bundle?

### ISSUE THREAD

**Issue by davidbernick** [intrigueio/intrigue-ident#3]
Ran build on the latest Dockerfile --
```
Step 9/10 : RUN bundle install
 ---> Running in f9e1e186a768
You must use Bundler 2 or greater with this lockfile.
The command '/bin/sh -c bundle install' returned a non-zero code: 20
```

**Comment by janmasarik** [comment]
I belive https://github.com/intrigueio/intrigue-ident/commit/8d3e1f4bb6ab997633878d97012af1d14bffc963 was the commit that broke Dockerfile. 

With my limited ruby knowledge, I'm now trying to come up with fix. Please let me know if you were able to make docker image working.

**Comment by janmasarik** [comment]
This is the (I belive temporary) solution: https://github.com/bundler/bundler/issues/6784#issuecomment-466180494

cc @jcran

**Comment by jcran** [comment]
the issue you're running into is probably system dependent - you presumably have bundler 1.x installed.

try this: ``` gem install bundler:2.0.2``` - this should install the latest version of bundler and get you to version 2.x  https://bundler.io/v2.0/guides/bundler_2_upgrade.html

Let me know if that doesn't do the trick. Regardless, i'l get this dockerized and pushed up to dockerhub in the near term.

**Comment by janmasarik** [comment]
Hey @jcran,

Haven't you possibly have the time to push it to dockerhub? 

I'm still failing to build it, this time with this error:  
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ident/.gem/gems/hitimes-1.3.1/ext/hitimes/c
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
./siteconf20190922-15-npss0x.rb extconf.rb
checking for clock_gettime() in -lrt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

**Comment by jcran** [comment]
Sorry for the delay, and thanks for your patience. I've just fixed a couple bugs with the current Docker setup, removed a couple deps: https://github.com/intrigueio/intrigue-ident/commit/d588e8d95694f5a4c49eb1a4a468225391e46e0d

Thanks to @retornam's work in the last month, the improved Dockerfile is better than my first attempts. 

Build like this: 
```
$ docker build . -t ident:latest
Sending build context to Docker daemon  4.658MB
 <snip>
```

Run like this: 
```
$ docker run -t ident:latest
Error! At least one of --file, --url, or --ip must be specified
```

Use like this: 
```
$ docker run -t ident:latest --url http://www.test.com
Checking URL: http://www.test.com
Fingerprint:
 - Nginx Nginx 1.16.1  - Nginx (CPE: cpe:2.3:a:nginx:nginx:1.16.1:) (Tags: ["Web Server"])
Content Checks:
 - Access-Control-Allow-Origin Header: false
 - P3P Header: true
 <snip>
```

**Comment by jcran** [comment]
Dockerhub pre-built image is now available here: https://hub.docker.com/r/intrigueio/intrigue-ident

**Comment by jcran** [comment]
Marking this closed for now, please re-open a ticket if you have any trouble!
