### ISSUE TITLE
false positive on open redirect check

### ISSUE THREAD

**Issue by digininja** [intrigueio/intrigue-ident#4]
Your open redirect check has this regex in it:

```
/\?url=http/i
```

But that is used by quite a few other things, on my site, most of the social media links match it:

```
<a title="Share on Twitter" id="twitter-share" href="https://twitter.com/share?text=DigiNinja&amp;url=https://digi.ninja/index.php" rel="noopener" target="_blank"><i class="fa fa-twitter"></i></a>
```

I think it is too vague a check to determine open redirect based off that. It also took me a while to track down why you thought there was an open redirect, maybe giving the reason for the decision would be good as it would help determine whether it is a false positive or not.

**Comment by jcran** [comment]
Awesome, thanks for ticketing. Agree, way too loose. It's been flagging on the oembed wp plugin too. Let me know if you have thoughts on specific items to tighten it up.

**Comment by digininja** [comment]
Maybe change the finding to "potential" and then log the suspicious URL.

That might but work with the way your
implementation though.

**Comment by jcran** [comment]
Functionality is deprecated, marking this as closed. Thanks again for the report @digininja
